#!/usr/bin/env python3
"""
ingest_full.py — Full corpus ingest for Mneme.

Walks skills + sessions + logs (the three directories the user asked for),
sends content to MiniMax M2.7 for LLM-assisted chunking + tag generation,
then embeds each chunk with Gemini Embedding 2 (768-dim) for semantic search.

Three-tier architecture (per SPEC.md):
  - LLM chunking + tagging  →  MiniMax M2.7  (cloud, fast, JSON-reliable)
  - Embeddings                →  Gemini Embedding 2  (cloud, 768-dim)
  - Intent detection          →  BitNet b1.58-2B-4T  (local, :8081)

This script:
  1. Collects files from skills/, sessions/, logs/ with per-source caps
  2. Chunks each file via MiniMax M2.7 (sequential, with retries)
  3. Embeds chunk content via Gemini Embedding 2 batched
  4. Writes to data/skill_chunks.jsonl  (append-only chunk store)
  5. Embeddings go alongside as "embedding": [...] in each chunk record

The 248 existing chunks in skill_chunks.jsonl come from a single skill
(afrexai-qa-testing-engine) and were generated by the old Gemini path.
We do NOT re-process them by default — pass --fresh to start over.

Crash recovery:
  - Append-only writes, so a kill -9 mid-run loses at most the in-flight batch
  - Per-file status is tracked in scripts/ingest_full_manifest.json
  - On restart, files marked "done" in the manifest are skipped

Usage:
  uv run python scripts/ingest_full.py                 # resume + new files
  uv run python scripts/ingest_full.py --fresh         # start over
  uv run python scripts/ingest_full.py --dry-run       # show what would run
  uv run python scripts/ingest_full.py --skills-only   # just skills/
"""
from __future__ import annotations

import argparse
import glob
import json
import logging
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

# ── Load .env the way the rest of Mneme does (workaround for known bug) ────
from dotenv import dotenv_values

_cfg = dotenv_values(Path(__file__).resolve().parent.parent / ".env")
for _k, _v in _cfg.items():
    if _v is not None:
        os.environ.setdefault(_k, _v)

# Mneme imports — must come AFTER env is loaded
from src.ingestion.llm_client import MiniMaxClient

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
log = logging.getLogger("ingest_full")

# ── Embedding client selection ─────────────────────────────────────────────
# EMBEDDING_PROVIDER=ollama → local qwen3-embedding:0.6b (no rate limits)
# EMBEDDING_PROVIDER=gemini → cloud Gemini Embedding 2 (default, 100 RPM cap)
# Default = ollama since it's free, local, and rate-limit-free on this server.


def make_embedding_client():
    provider = os.environ.get("EMBEDDING_PROVIDER", "ollama").lower()
    if provider == "ollama":
        from src.retrieval.ollama_embeddings import OllamaEmbeddingClient
        return OllamaEmbeddingClient(), "ollama"
    elif provider == "gemini":
        from src.embedding.gemini_client import GeminiEmbeddingClient, GeminiEmbeddingError
        return GeminiEmbeddingClient(), "gemini"
    else:
        raise RuntimeError(
            f"Unknown EMBEDDING_PROVIDER: {provider!r}. Use 'ollama' or 'gemini'."
        )

# ── Paths and constants ─────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
DATA_DIR.mkdir(exist_ok=True)
CHUNKS_PATH = DATA_DIR / "skill_chunks.jsonl"
MANIFEST_PATH = PROJECT_ROOT / "scripts" / "ingest_full_manifest.json"

# Three target directories (per user prompt: "skills, sessions, Logs")
SKILLS_ROOT = "/home/Hermes/.hermes/skills"
SESSIONS_ROOT = "/home/Hermes/.hermes/sessions"
LOGS_ROOT = "/home/Hermes/.hermes/logs"

# Per-source caps — keep chunks bounded so MiniMax gets a sane prompt size.
MAX_CHARS_SKILL = 12_000       # SKILL.md files are usually < 8K
MAX_CHARS_SESSION = 8_000      # JSONL/JSON sessions can be huge, truncate
MAX_CHARS_LOG = 6_000          # logs are typically long, truncate aggressively

# LLM call pacing — MiniMax M2.7 has higher limits than free Gemini
MINIMAX_DELAY_BETWEEN = 1.5    # seconds between LLM chunking calls
EMBEDDING_BATCH_SIZE = 50      # Gemini batch size (vectors per call)
EMBEDDING_BATCH_DELAY = 1.5    # seconds between embedding batches (cool down Gemini)
DEFAULT_WORKERS = 3            # conservative default to avoid Gemini 429s

# File extension filters per directory
SKILL_EXTS = {".md", ".py", ".sh", ".json", ".yaml", ".yml", ".toml", ".txt"}
SESSION_EXTS = {".jsonl", ".json"}
LOG_EXTS = {".log", ".md", ".txt"}

# Files we never want to index
SKIP_PATTERNS = (
    "__pycache__",
    ".pyc",
    ".git/",
    "node_modules/",
    ".venv/",
    "prd/",
    "logs/",
)


# ── Manifest helpers ────────────────────────────────────────────────────────

def load_manifest() -> dict[str, str]:
    """Return {file_path: status} — status ∈ {"done", "failed"}."""
    if MANIFEST_PATH.exists():
        try:
            return json.loads(MANIFEST_PATH.read_text())
        except json.JSONDecodeError:
            log.warning("manifest corrupt, starting fresh")
    return {}


def save_manifest(manifest: dict[str, str]) -> None:
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, sort_keys=True))


# ── File collection ─────────────────────────────────────────────────────────

def collect_skills() -> list[Path]:
    return [
        Path(p) for p in glob.glob(os.path.join(SKILLS_ROOT, "**", "*"), recursive=True)
        if Path(p).is_file()
        and Path(p).suffix in SKILL_EXTS
        and not any(s in str(p) for s in SKIP_PATTERNS)
    ]


def collect_sessions() -> list[Path]:
    return [
        Path(p) for p in glob.glob(os.path.join(SESSIONS_ROOT, "*"), recursive=False)
        if Path(p).is_file() and Path(p).suffix in SESSION_EXTS
    ]


def collect_logs() -> list[Path]:
    found: list[Path] = []
    # Top-level logs/
    for p in glob.glob(os.path.join(LOGS_ROOT, "*")):
        pp = Path(p)
        if pp.is_file() and pp.suffix in LOG_EXTS:
            found.append(pp)
    # Subdirs (curator/, etc) — only index REPORT.md and run.json, not raw logs
    for p in glob.glob(os.path.join(LOGS_ROOT, "*", "*.md")):
        found.append(Path(p))
    for p in glob.glob(os.path.join(LOGS_ROOT, "*", "*.json")):
        if "REPORT" in str(p) or "run.json" in str(p):
            found.append(Path(p))
    return found


def read_capped(path: Path, cap: int) -> str:
    """Read file, capped to `cap` chars, with a truncation notice prepended."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        log.warning("read_failed path=%s err=%s", path, exc)
        return ""
    if len(text) > cap:
        return text[:cap] + f"\n\n[... truncated at {cap} chars, original was {len(text)} ...]"
    return text


# ── JSONL session serialization ─────────────────────────────────────────────

def session_to_text(path: Path) -> str:
    """Convert a session JSONL/JSON file to a flat text representation
    that the LLM can actually chunk. We extract user/assistant turns."""
    if path.suffix == ".jsonl":
        turns = []
        try:
            with path.open() as f:
                for i, line in enumerate(f):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    role = rec.get("role", "?")
                    msg = rec.get("content", rec.get("message", ""))
                    if isinstance(msg, list):
                        msg = " ".join(
                            m.get("text", str(m)) if isinstance(m, dict) else str(m)
                            for m in msg
                        )
                    if msg:
                        turns.append(f"[{role}] {msg[:1500]}")
                    if i > 200:  # cap turn count
                        break
        except Exception as exc:
            log.warning("session_read_failed path=%s err=%s", path, exc)
        return "\n\n".join(turns)

    if path.suffix == ".json":
        # session_*.json — full session dump, extract messages array
        try:
            data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
            if isinstance(data, dict):
                msgs = data.get("messages", [])
                if msgs and isinstance(msgs, list):
                    turns = []
                    for m in msgs[:200]:
                        if isinstance(m, dict):
                            role = m.get("role", "?")
                            content = m.get("content", "")
                            if isinstance(content, list):
                                content = " ".join(
                                    c.get("text", str(c)) if isinstance(c, dict) else str(c)
                                    for c in content
                                )
                            if content:
                                turns.append(f"[{role}] {content[:1500]}")
                    return "\n\n".join(turns)
                # Fallback: just dump the first few keys
                return json.dumps({k: str(v)[:500] for k, v in list(data.items())[:10]}, indent=2)
        except Exception as exc:
            log.warning("session_json_failed path=%s err=%s", path, exc)
        return ""

    return ""


# ── Heuristic fallback chunker ──────────────────────────────────────────────

def heuristic_chunk(content: str, file_path: str) -> list[dict[str, Any]]:
    """Split content into chunks by paragraph when the LLM returns garbage.

    Used as a last-resort fallback so a single bad MiniMax response doesn't
    lose the whole file from the corpus. Tags are derived from filename and
    content keywords — far less rich than LLM tags but always present.
    """
    if not content or not content.strip():
        return []

    paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
    if not paragraphs:
        paragraphs = [content[:2000]]

    chunks: list[dict[str, Any]] = []
    chunk_size = 1500  # chars per chunk
    buffer = ""
    chunk_idx = 0
    for p in paragraphs:
        if len(buffer) + len(p) > chunk_size and buffer:
            chunks.append({
                "chunk_id": f"heur_c{chunk_idx:03d}",
                "content": buffer,
                "page_order": chunk_idx,
                "tags": ["outcome=work_done", "source=heuristic"],
                "source_file": file_path,
                "analysis_notes": "Heuristic fallback — MiniMax returned unparseable output.",
            })
            chunk_idx += 1
            buffer = ""
        buffer += p + "\n\n"
    if buffer.strip():
        chunks.append({
            "chunk_id": f"heur_c{chunk_idx:03d}",
            "content": buffer,
            "page_order": chunk_idx,
            "tags": ["outcome=work_done", "source=heuristic"],
            "source_file": file_path,
            "analysis_notes": "Heuristic fallback — MiniMax returned unparseable output.",
        })

    return chunks


# ── Core ingest loop ───────────────────────────────────────────────────────

def process_file(
    path: Path,
    source_kind: str,
    minimax: MiniMaxClient,
    embeddings,
    provider_kind: str,
    cap: int,
) -> list[dict[str, Any]]:
    """Chunk + embed one file. Returns list of chunk records (without manifest
    metadata — that's added by the caller before writing).

    On MiniMax JSON parse failure, falls back to heuristic paragraph chunking
    so the file is still represented in the corpus (with `source=heuristic` tag).
    """
    if source_kind == "session":
        content = session_to_text(path)
    else:
        content = read_capped(path, cap)

    if not content or not content.strip():
        return []

    # Try MiniMax chunking first
    try:
        result = minimax.chunk_content(content, file_path=str(path))
        chunk_dicts = result.chunks
        cross_rels = result.cross_chunk_relationships
    except Exception as exc:
        log.warning("minimax_fallback_heuristic path=%s err=%s", path, exc)
        chunk_dicts = heuristic_chunk(content, str(path))
        cross_rels = []

    if not chunk_dicts:
        return []

    # Embed each chunk's content. SKIP_EMBEDDINGS env var disables this entirely
    # so we can focus on chunking throughput without hitting Gemini RPM caps.
    skip_embeddings = os.environ.get("MNEME_SKIP_EMBEDDINGS", "").lower() in ("1", "true", "yes")
    if skip_embeddings:
        vectors = [None] * len(chunk_dicts)
    else:
        texts = [c.get("content", "")[:2000] for c in chunk_dicts]
        try:
            vectors = embeddings.embed_batch(texts)
            # Cool-down: only meaningful for cloud providers (Gemini rate limits).
            # Local Ollama needs no delay — let it rip.
            if provider_kind == "gemini":
                time.sleep(EMBEDDING_BATCH_DELAY)
        except Exception as exc:
            log.warning("embedding_failed path=%s err=%s — chunks without vectors", path, exc)
            vectors = [None] * len(chunk_dicts)

    records = []
    for chunk, vec in zip(chunk_dicts, vectors):
        rec = dict(chunk)
        rec["source_file"] = str(path)
        rec["source_kind"] = source_kind
        # Embedding fields are provider-agnostic — both clients expose _model
        # and embed_batch() returns list[list[float]].
        rec["embedding_model"] = getattr(embeddings, "_model", None) if vec else None
        rec["embedding_dim"] = len(vec) if vec else None
        rec["embedding"] = vec
        rec["linked_chunks"] = [
            r["target_chunk_id"]
            for r in cross_rels
            if r["source_chunk_id"] == chunk["chunk_id"]
        ]
        records.append(rec)

    time.sleep(MINIMAX_DELAY_BETWEEN)
    return records


# ── Main ────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fresh", action="store_true",
                    help="ignore manifest, re-process all files")
    ap.add_argument("--dry-run", action="store_true",
                    help="list files that would be processed, don't ingest")
    ap.add_argument("--skills-only", action="store_true")
    ap.add_argument("--sessions-only", action="store_true")
    ap.add_argument("--logs-only", action="store_true")
    ap.add_argument("--limit", type=int, default=0,
                    help="process at most N files (0 = no limit)")
    ap.add_argument("--workers", type=int, default=DEFAULT_WORKERS,
                    help=f"concurrent file ingestion threads (default {DEFAULT_WORKERS})")
    args = ap.parse_args()

    # Collect sources
    sources: list[tuple[Path, str, int]] = []
    if not args.sessions_only and not args.logs_only:
        sources.extend((p, "skill", MAX_CHARS_SKILL) for p in collect_skills())
    if not args.skills_only and not args.logs_only:
        sources.extend((p, "session", MAX_CHARS_SESSION) for p in collect_sessions())
    if not args.skills_only and not args.sessions_only:
        sources.extend((p, "log", MAX_CHARS_LOG) for p in collect_logs())

    # De-duplicate
    sources = list({(p.resolve(), k, c) for p, k, c in sources if p.exists()})
    sources.sort(key=lambda x: str(x[0]))

    log.info("collected=%d sources (skills+sessions+logs)", len(sources))
    by_kind: dict[str, int] = {}
    for _, k, _ in sources:
        by_kind[k] = by_kind.get(k, 0) + 1
    log.info("breakdown: %s", by_kind)

    # Manifest
    manifest = {} if args.fresh else load_manifest()
    pending = [
        (p, k, c) for p, k, c in sources
        if str(p) not in manifest or manifest[str(p)] != "done"
    ]
    log.info("pending=%d (already done=%d)", len(pending), len(sources) - len(pending))

    if args.limit:
        pending = pending[: args.limit]
        log.info("limited to first %d files", args.limit)

    if args.dry_run:
        for p, k, c in pending[:50]:
            print(f"  [{k}] {p}")
        if len(pending) > 50:
            print(f"  ... and {len(pending) - 50} more")
        return 0

    # Init clients
    try:
        minimax = MiniMaxClient()
        embeddings, provider_kind = make_embedding_client()
    except Exception as exc:
        log.error("client_init_failed err=%s", exc)
        return 1

    log.info("minimax model=%s base=%s", minimax._model, minimax._base_url)
    log.info("embeddings provider=%s model=%s", provider_kind, getattr(embeddings, "_model", "?"))
    log.info("workers=%d", args.workers)

    # Load existing chunks (so we can append, not overwrite)
    existing_chunk_ids: set[str] = set()
    if CHUNKS_PATH.exists() and not args.fresh:
        with CHUNKS_PATH.open() as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    existing_chunk_ids.add(rec.get("chunk_id", ""))
                except json.JSONDecodeError:
                    continue
        log.info("existing_chunks=%d (will dedupe by chunk_id)", len(existing_chunk_ids))

    # Thread-safe write lock for chunks file
    import threading
    write_lock = threading.Lock()

    def write_records(records: list[dict[str, Any]]) -> int:
        """Append records to chunks file, return count actually written (post-dedupe)."""
        written = 0
        with write_lock:
            with CHUNKS_PATH.open("a") as out:
                for rec in records:
                    raw_id = rec.get("chunk_id", f"c{written:03d}")
                    safe_path = str(rec["source_file"]).replace("/", "_").replace(".", "_")[:60]
                    unique_id = f"{safe_path}__{raw_id}"
                    if unique_id in existing_chunk_ids:
                        continue
                    rec["chunk_id"] = unique_id
                    rec["session_id"] = "mneme-full-corpus-2026-06-19"
                    rec["project_root"] = "/home/Hermes"
                    rec["created_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
                    tags = rec.get("tags", [])
                    rec["outcome_tag"] = next(
                        (t.split("=", 1)[1] for t in tags if t.startswith("outcome=")),
                        "work_done",
                    )
                    out.write(json.dumps(rec) + "\n")
                    existing_chunk_ids.add(unique_id)
                    written += 1
                out.flush()
        return written

    def process_one(idx: int, total: int, path: Path, kind: str, cap: int) -> tuple[Path, int, str | None]:
        """Process one file. Returns (path, chunks_added, error_msg)."""
        try:
            records = process_file(path, kind, minimax, embeddings, provider_kind, cap)
        except Exception as exc:
            log.warning("file_failed path=%s err=%s", path, exc)
            return (path, 0, str(exc))
        n = write_records(records)
        return (path, n, None)

    # Stats
    started = time.time()
    chunks_added = 0
    chunks_skipped_dup = 0
    files_done = 0
    files_failed = 0

    # Truncate chunks file if --fresh
    if args.fresh:
        log.info("starting fresh, truncating %s", CHUNKS_PATH)
        CHUNKS_PATH.write_text("")

    # Submit all tasks to a thread pool. Each worker calls MiniMax sequentially
    # within its own thread (so we get parallelism without hammering the API).
    log.info("submitting %d tasks to %d workers...", len(pending), args.workers)
    completed = 0
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {
            pool.submit(process_one, i + 1, len(pending), path, kind, cap): (i, path, kind)
            for i, (path, kind, cap) in enumerate(pending)
        }
        try:
            for fut in as_completed(futures):
                i, path, kind = futures[fut]
                completed += 1
                try:
                    p, n, err = fut.result()
                except Exception as exc:
                    log.warning("future_failed path=%s err=%s", path, exc)
                    manifest[str(path)] = "failed"
                    files_failed += 1
                    continue

                if err is not None:
                    manifest[str(path)] = "failed"
                    files_failed += 1
                else:
                    manifest[str(path)] = "done"
                    chunks_added += n
                    files_done += 1

                elapsed = time.time() - started
                rate = completed / elapsed if elapsed > 0 else 0
                eta_sec = (len(pending) - completed) / rate if rate > 0 else 0
                log.info(
                    "[%d/%d] [%s] %s +%d chunks | total=%d done=%d failed=%d "
                    "elapsed=%.0fs rate=%.2f f/s eta=%.0fs (%.0f min)",
                    completed, len(pending), kind, path.name, n,
                    chunks_added, files_done, files_failed,
                    elapsed, rate, eta_sec, eta_sec / 60,
                )

                # Save manifest every 20 files
                if completed % 20 == 0:
                    save_manifest(manifest)

        except KeyboardInterrupt:
            log.warning("interrupted, saving manifest and waiting for in-flight tasks")
            # Don't cancel — let in-flight finish writing what they have
        finally:
            save_manifest(manifest)

    log.info(
        "DONE files_done=%d files_failed=%d chunks_added=%d elapsed=%.0fs "
        "(%.1f min)",
        files_done, files_failed, chunks_added,
        time.time() - started, (time.time() - started) / 60,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
