"""
In-memory models matching the Neo4j data model.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class OutcomeTag(str, Enum):
    """Outcome tag — tracks what happened when this chunk was 'executed'."""

    WORK_DONE = "work_done"
    NO_TOOL_CALLED = "no_tool_called"
    SUCCESSFULLY_CALLED = "successfully_called"
    FAILED = "failed"
    STOPPED = "stopped"


OUTCOME_PRIORITY = {
    OutcomeTag.FAILED: 1.0,
    OutcomeTag.STOPPED: 0.8,
    OutcomeTag.WORK_DONE: 0.6,
    OutcomeTag.SUCCESSFULLY_CALLED: 0.4,
    OutcomeTag.NO_TOOL_CALLED: 0.2,
}


class RelationshipType(str, Enum):
    """Graph edge types — how two chunks relate."""

    SAME_TOOL_CALL = "same_tool_call"
    PREREQUISITE = "prerequisite"
    FOLLOWS = "follows"
    CONTRADICTS = "contradicts"
    SAME_CONCEPT = "same_concept"


class TagTree(BaseModel):
    """
    Parsed tag hierarchy generated by LLM during ingestion.
    Level 1 (category):  tool | memory | skill | context
    Level 2 (entity):    auth | db | http | file_io | ...
    Level 3 (outcome):   failed | successfully_called | no_tool_called | stopped
    Level 4 (error):     token_expired | timeout | auth_rejected | ...
    """

    category: str = Field(default="tool", description="Level 1: tool | memory | skill | context")
    entity: str | None = Field(default=None, description="Level 2: auth, db, http, ...")
    outcome: str | None = Field(default=None, description="Level 3: failed, successfully_called, ...")
    error: str | None = Field(default=None, description="Level 4: token_expired, timeout, ...")


class MemoryChunk(BaseModel):
    """
    Core memory record — the atomic unit of memory in Mneme.

    Attributes:
        chunk_id: Unique identifier, e.g. "mem_001"
        session_id: Conversation file path — the session this chunk belongs to
        project_root: Git repo root for namespace isolation
        content: The actual chunk text
        page_order: Position within the source file (page/linear index)
        tags: Flat tag list, e.g. ["tool=auth", "outcome=failed", "error=token_expired"]
        tag_tree: Parsed hierarchical tags
        linked_chunks: Graph edges — IDs of related chunks
        outcome_tag: The primary outcome classification
        source_file: Absolute path of the source file this chunk came from
        created_at: When this chunk was first stored
        last_accessed: Last time this chunk was retrieved (for recency boost)
    """

    chunk_id: str
    session_id: str
    project_root: str

    content: str
    page_order: int = 0

    tags: list[str] = Field(default_factory=list)
    tag_tree: TagTree = Field(default_factory=TagTree)
    linked_chunks: list[str] = Field(default_factory=list)

    outcome_tag: OutcomeTag = OutcomeTag.WORK_DONE
    source_file: str | None = None

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_accessed: datetime | None = None

    model_config = {
        "use_enum_values": True,
    }

    def to_dict(self) -> dict[str, Any]:
        """Serialize to plain dict — matches the API response shape."""
        return {
            "chunk_id": self.chunk_id,
            "session_id": self.session_id,
            "project_root": self.project_root,
            "content": self.content,
            "page_order": self.page_order,
            "tags": self.tags,
            "tag_tree": self.tag_tree.model_dump(),
            "linked_chunks": self.linked_chunks,
            "outcome_tag": self.outcome_tag,
            "source_file": self.source_file,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "last_accessed": (
                self.last_accessed.isoformat() if self.last_accessed else None
            ),
        }


class ChunkRelationship(BaseModel):
    """
    A directed edge in the cross-chunk graph.
    Created by the LLM during ingestion to capture relationships between chunks.
    """

    source_chunk_id: str
    target_chunk_id: str
    relationship_type: RelationshipType
    reason: str = Field(
        default="",
        description="LLM-provided explanation of why these chunks are related",
    )

    model_config = {
        "use_enum_values": True,
    }

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_chunk_id": self.source_chunk_id,
            "target_chunk_id": self.target_chunk_id,
            "relationship_type": self.relationship_type,
            "reason": self.reason,
        }


# ── Helper constructors ───────────────────────────────────────────────────────

import threading

_counter = 0
_counter_lock = threading.Lock()


def next_chunk_id() -> str:
    """Generate the next chunk ID, thread-safely.

    [SECURITY/PRODUCTION] Uses a threading.Lock to prevent race conditions
    when multiple worker processes or threads call this concurrently.
    Note: lock protects within a single process. For multi-process
    deployments, use UUIDs or a database sequence.
    """
    global _counter
    with _counter_lock:
        _counter += 1
        return f"mem_{_counter:03d}"
